erDiagram

    Action {
        number id PK
        string name
        string nextActivityName
    }

    ActivityLog {
        number id PK
        string activityName
        string action
        Date actionDate
        string actionBy
        string actionByDisplayName
        string comment
    }

    Activity {
        number id PK
        string name
    }

    CertificateDocumentType {
        number id PK
        string code
        string name
        number stfsId
    }

    DocumentType {
        number id PK
        string code
        string name
        ReferenceDocumentGroupEnum group
    }

    FarmerInfo {
        number id PK
    }

    FarmerLand {
        number id PK
        string no
        string ref
        string status
        number statusFlag
        boolean isValidatingStatus
        boolean isFarmerRelatedToFarmBookOwner
        Date dataDate
        string stfsGid
    }

    FarmerRegistrationType {
        number id PK
        string code
        string name
    }

    History {
        string action
        string actionBy
        Date actionDate
    }

    MModule {
        number id PK
    }

    ProcurementRecord {
        number id PK
        string title
        string submissionId
        string jotFormSubmissionId
        Date fillDate
        string referenceNo
        int type
        string farmerPersonCode
        string teamCode
        string userCode
        string verifiedBy
        string verifiedByName
        Date verifiedDate
        Date firstAssignedDate
        string firstAssignedTo
        Date latestAssignedDate
        boolean isVendorInvalid
        boolean isVendorVerified
        boolean isBypass
        boolean isPendingVerified
        string status
        number statusFlag
        string assignee
        Date dataDate
    }

    ReferenceDocument {
        string id PK
        string fileName
        string fileType
        string url
        string fileId
        boolean isDeletable
        boolean confirmed
        Date dataDate
        string status
        number statusFlag
    }

    ReferenceInfo {
        number id PK
        ReferenceInfoTypeEnum infoType
        string field
        string value
        number correctionPercent
    }

    RpaUser {
        number id PK
        string phone
        string code
        string accountName
        boolean isActive
        simple_array type
    }

    RubberVariety {
        number id PK
        string name
        number countryId
        number stfsId
    }

    SelectedReferenceInfo {
        number procurementRecordId PK
    }

    SubModule {
        number id PK
        string code
        string name
    }

    Task {
        string id PK
        string serialNo
        string referenceNo
        string title
        string activityName
        Date assignedDate
        Date dueDate
        number taskAssigning
        string moduleCode
        number moduleId
        string subModuleCode
        number subModuleId
    }

    Action }o--|| MModule : "e"
    Action }o--|| SubModule : "e"
    Action }o--|| Activity : "e"
    ActivityLog }o--|| ProcurementRecord : "e"
    ActivityLog }o--|| FarmerLand : "e"
    Activity }o--|| MModule : "e"
    Activity }o--|| SubModule : "e"
    Activity ||--o{ Action : "actionList"
    CertificateDocumentType }o--|| MModule : "e"
    CertificateDocumentType }o--|| MModule : "e"
    DocumentType }o--|| MModule : "e"
    DocumentType }o--|| SubModule : "e"
    DocumentType ||--o{ ReferenceDocument : "referenceDocumentList"
    FarmerLand ||--o{ ActivityLog : "activityLogList"
    FarmerLand ||--o{ ReferenceDocument : "referenceDocumentList"
    FarmerRegistrationType }o--|| MModule : "e"
    FarmerRegistrationType }o--|| MModule : "e"
    ProcurementRecord }o--|| FarmerInfo : "e"
    ProcurementRecord ||--o{ FarmerLand : "farmerLandList"
    ProcurementRecord ||--o{ ActivityLog : "activityLogList"
    ProcurementRecord ||--o{ ReferenceDocument : "referenceDocumentList"
    ReferenceDocument }o--|| ProcurementRecord : "e"
    ReferenceDocument }o--|| FarmerLand : "e"
    ReferenceDocument }o--|| FarmerInfo : "e"
    ReferenceDocument }o--|| DocumentType : "e"
    RpaUser ||--o{ ActivityLog : "activityList"
    SubModule }o--|| MModule : "e"
    SubModule ||--o{ DocumentType : "documentTypeList"
    SubModule ||--o{ FarmerRegistrationType : "farmerRegistrationTypeList"
    SubModule ||--o{ CertificateDocumentType : "certificateDocumentTypeList"
    SubModule ||--o{ Activity : "activityList"
    SubModule ||--o{ Action : "actionList"
